### PR TITLE
Push flows to ntopng

### PR DESCRIPTION
**Pull request by deece**
Ntopng is a an open-source traffic analyser:
https://www.ntop.org/products/traffic-analysis/ntop/

Unfortunately, it cannot ingest Netflow data directly, instead,
it requires a payware component (Nprobe) to tranlate Netflow to JSON
encapsulated in ZeroMQ messages.

This patch allows softflowd to generate those messages directly,
allowing Ntopng to be used without the need for the payware component.

Signed-off-by: Alastair D'Silva <alastair@d-silva.org>

### CODE REVIEW

**Comment by tusc** [comment]
Does anyone know what version of ntop supports this? I've tried to different ones from 3.x and 4.x with no luck.

**Comment by vostorga** [comment]
Hi

In May I tried to push flows to ntop  but the maintainer explained to me in
ticket #25 that this functionality doesn't exist.

Kind regards,

**Comment by deece** [comment]
This path exports data to ntopng, not ntop, they are different codebase.

**Comment by vostorga** [comment]
Yes, I tried without success to use softflowd instead of nprobe to
export/transform flows to ntopng.

Regards

**Comment by tusc** [comment]
@deece , I meant to say ntopng, not ntop. Regardless it does not work with ntopng 3.x or 4.x. Is there a version it is intended to work with?

**Comment by migube** [comment]
hi guys
does it work to ntopng?

**Pull request merged**
